### ISSUE TITLE
大佬可以兼容到 .net framework 3.5 ?

### ISSUE THREAD

**Issue by gaoconggit** [kklldog/AgileConfig.Client4FR#1]

**Comment by kklldog** [comment]
啊 这。。。很难啊，应为依赖的包都不支持3.5 。。。

**Comment by gaoconggit** [comment]
https://github.com/kerryjiang/SuperWebSocket  ，这个项目支持 3.5 。

**Comment by gaoconggit** [comment]
WebSocket4Net 和  SuperWebSocket 是同一个作者捏

**Comment by kklldog** [comment]
有时间再弄，你们也可以自己动动手啊。。。

**Comment by gaoconggit** [comment]
我写了一个.net framework 3.5 版本的。 一会 pull request 您看看

**Comment by kklldog** [comment]
#2 
close
